/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_ac_univie_gameclient_video_VideoGLSurfaceView_GLRenderer */

#ifndef _Included_at_ac_univie_gameclient_video_VideoGLSurfaceView_GLRenderer
#define _Included_at_ac_univie_gameclient_video_VideoGLSurfaceView_GLRenderer
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
