/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class at_ac_univie_gameclient_video_VideoGLSurfaceView */

#ifndef _Included_at_ac_univie_gameclient_video_VideoGLSurfaceView
#define _Included_at_ac_univie_gameclient_video_VideoGLSurfaceView
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     at_ac_univie_gameclient_video_VideoGLSurfaceView
 * Method:    native_start
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_ac_univie_gameclient_video_VideoGLSurfaceView_native_1start
  (JNIEnv *, jobject);

/*
 * Class:     at_ac_univie_gameclient_video_VideoGLSurfaceView
 * Method:    native_gl_resize
 * Signature: (II)V
 */
JNIEXPORT void JNICALL Java_at_ac_univie_gameclient_video_VideoGLSurfaceView_native_1gl_1resize
  (JNIEnv *, jobject, jint, jint);

/*
 * Class:     at_ac_univie_gameclient_video_VideoGLSurfaceView
 * Method:    native_gl_render
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_ac_univie_gameclient_video_VideoGLSurfaceView_native_1gl_1render
  (JNIEnv *, jobject);

/*
 * Class:     at_ac_univie_gameclient_video_VideoGLSurfaceView
 * Method:    native_init
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_at_ac_univie_gameclient_video_VideoGLSurfaceView_native_1init
  (JNIEnv *, jobject, jstring);

/*
 * Class:     at_ac_univie_gameclient_video_VideoGLSurfaceView
 * Method:    destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_at_ac_univie_gameclient_video_VideoGLSurfaceView_destroy
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
